In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split

In [58]:
df=pd.read_csv("/Users/apple/Desktop/internship_2nd_year/machine learniing/bikes/bikesencoded.csv")

In [59]:
df

price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      1
1     119900.0     11000.0      1  4.0  350.0      2
2     600000.0       110.0      1  8.0  675.0      3
3      65000.0     16329.0      1  4.0  180.0      1
4      80000.0     10000.0      1  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
7319   25000.0     48587.0      1  8.0  150.0      6
7320   35000.0     60000.0      1  9.0  220.0      6
7321  450000.0      3430.0      1  4.0  750.0     14
7322  139000.0     21300.0      1  4.0  400.0      6
7323   80000.0      7127.0      1  5.0  220.0      6

[7324 rows x 6 columns]

In [60]:
x=df.drop('price',axis=1)
y=df[['price']]

In [61]:
y

price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7319   25000.0
7320   35000.0
7321  450000.0
7322  139000.0
7323   80000.0

[7324 rows x 1 columns]

In [62]:
x

kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
7319     48587.0      1  8.0  150.0      6
7320     60000.0      1  9.0  220.0      6
7321      3430.0      1  4.0  750.0     14
7322     21300.0      1  4.0  400.0      6
7323      7127.0      1  5.0  220.0      6

[7324 rows x 5 columns]

In [63]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [64]:
x_train

kms_driven  owner   age  power  brand
4506     68857.0      1  15.0  110.0      1
2758      5740.0      1   6.0  500.0      2
640      28329.0      1   6.0  110.0      6
5824     42966.0      1   7.0  150.0      4
6703      8000.0      1   5.0  500.0      2
...          ...    ...   ...    ...    ...
5191     56000.0      1   9.0  200.0      6
5226     22493.0      1   5.0  500.0      2
5390     17477.0      1   5.0  150.0      6
860      14836.0      1   8.0  150.0      4
7270      8000.0      1  10.0  250.0      5

[5859 rows x 5 columns]

In [65]:
y_train

price
4506   18000.0
2758  140000.0
640    32000.0
5824   40000.0
6703  160000.0
...        ...
5191   48928.0
5226  114000.0
5390   41000.0
860    40000.0
7270   80000.0

[5859 rows x 1 columns]

In [66]:
x_test

kms_driven  owner   age  power  brand
3795     22500.0      1   6.0  350.0      2
1562      3198.0      1   5.0  500.0      2
4480     15000.0      1   6.0  220.0      6
3718     27000.0      1  12.0  150.0      4
5887     16764.0      1   9.0  100.0      6
...          ...    ...   ...    ...    ...
4417     16523.0      1   5.0  750.0     14
527       2881.0      1   7.0  250.0     13
3309     23833.0      1   4.0  150.0      7
5077      9282.0      1   7.0  500.0      2
565       2980.0      1   6.0  160.0      1

[1465 rows x 5 columns]

In [67]:
y_test

price
3795   88400.0
1562  102850.0
4480   67000.0
3718   30000.0
5887   20000.0
...        ...
4417  395000.0
527   140000.0
3309   54500.0
5077  114000.0
565    36000.0

[1465 rows x 1 columns]

In [68]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((5859, 5), (5859, 1), (1465, 5), (1465, 1))

In [69]:
from sklearn.linear_model import LinearRegression

In [70]:
lr=LinearRegression()

In [71]:
lr.fit(x_train,y_train)

LinearRegression()

In [72]:
lr.score(x_train,y_train)

0.7114665793322051

In [73]:
lr.score(x_test,y_test)

0.763460600227799

In [74]:
pred=lr.predict(x_test)

In [75]:
pred

array([[123488.97495228],
       [214357.98885593],
       [ 93182.81403327],
       ...,
       [ 70536.47887982],
       [206616.18698751],
       [  5816.45900694]])

In [77]:
df=pd.read_csv("/Users/apple/Desktop/internship_2nd_year/machine learniing/laptop/laptopassignment.csv")

In [78]:
df

brand  processor_brand  processor_name  processor_gnrtn  ram_gb   ssd  \
0        0                0               0               10       4     0   
1        1                0               0               10       4     0   
2        1                0               0               10       4     0   
3        0                0               1               10       8   512   
4        0                0               2               99       4     0   
..     ...              ...             ...              ...     ...   ...   
777      0                1              10               99       4  1024   
778      0                1              10               99       4  1024   
779      0                1              10               99       4  1024   
780      0                1              10               99       4  1024   
781      1                1               3               10       8   512   

      hdd  graphic_card_gb  warranty  Touchscreen   Price  rating  
0    1024                0         0            0   34649       2  
1    1024                0         0            0   38999       3  
2    1024                0         0            0   39999       3  
3       0                2         0            0   69990       3  
4     512                0         0            0   26990       3  
..    ...              ...       ...          ...     ...     ...  
777     0                0         1            0  135990       3  
778     0                0         1            0  144990       3  
779     0                4         1            0  149990       3  
780     0                4         1            0  142990       3  
781     0                0         0            0   57490       4  

[782 rows x 12 columns]

In [79]:
x_train

kms_driven  owner   age  power  brand
4506     68857.0      1  15.0  110.0      1
2758      5740.0      1   6.0  500.0      2
640      28329.0      1   6.0  110.0      6
5824     42966.0      1   7.0  150.0      4
6703      8000.0      1   5.0  500.0      2
...          ...    ...   ...    ...    ...
5191     56000.0      1   9.0  200.0      6
5226     22493.0      1   5.0  500.0      2
5390     17477.0      1   5.0  150.0      6
860      14836.0      1   8.0  150.0      4
7270      8000.0      1  10.0  250.0      5

[5859 rows x 5 columns]

In [80]:
y_train

price
4506   18000.0
2758  140000.0
640    32000.0
5824   40000.0
6703  160000.0
...        ...
5191   48928.0
5226  114000.0
5390   41000.0
860    40000.0
7270   80000.0

[5859 rows x 1 columns]

In [81]:
x_test

kms_driven  owner   age  power  brand
3795     22500.0      1   6.0  350.0      2
1562      3198.0      1   5.0  500.0      2
4480     15000.0      1   6.0  220.0      6
3718     27000.0      1  12.0  150.0      4
5887     16764.0      1   9.0  100.0      6
...          ...    ...   ...    ...    ...
4417     16523.0      1   5.0  750.0     14
527       2881.0      1   7.0  250.0     13
3309     23833.0      1   4.0  150.0      7
5077      9282.0      1   7.0  500.0      2
565       2980.0      1   6.0  160.0      1

[1465 rows x 5 columns]

In [82]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((5859, 5), (5859, 1), (1465, 5), (1465, 1))

In [83]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [84]:
lr=LinearRegression()

In [85]:
lr.fit(x_train,y_train)

LinearRegression()

In [86]:
lr.score(x_train,y_train)

0.7114665793322051

In [87]:
from sklearn.svm import SVR
svg=SVR()
svg.fit(x_train,y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [88]:
svg.score(x_train,y_train)

-0.06147776781317571

In [89]:
from sklearn.svm import SVC
svc_obj=SVC()
from sklearn.datasets import load_iris
x,y=load_iris(return_X_y=True)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2,)
svc_obj.fit(x_train,y_train)
svc_obj.score(x_train,y_train)
svc_obj.score(x_test,y_test)

1.0

In [90]:
svc_obj.predict(x_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [91]:
# KNN

from sklearn.neighbors import KNeighborsClassifier
knn_obj=KNeighborsClassifier()
knn_obj.fit(x_train,y_train)
knn_obj.score(x_train,y_train)
knn_obj.score(x_test,y_test)



1.0

In [92]:
knn_obj.score(x_train,y_train)

0.9666666666666667

In [93]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor()
knn.fit(x_train,y_train)


KNeighborsRegressor()

In [94]:
knn.score(x_train,y_train)

0.9635404578542041

In [95]:
knn.score(x_test,y_test)

0.9885532591414944

In [96]:
from sklearn.tree import DecisionTreeClassifier
dtr=DecisionTreeClassifier()
dtr.fit(x_train,y_train)

DecisionTreeClassifier()

In [97]:
dtr.score(x_train,y_train)

1.0

In [98]:
dtr.score(x_test,y_test)

1.0

In [99]:
dtr.predict(x_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])